logging:
  level.org.springframework: TRACE
  level.one.microstream: DEBUG
  file:
    path: logs
    
one.microstream:
   storage-directory: ./stateData
   backup-directory: ./stateDataBackup
   channel-count: 1
   housekeeping-interval: 10000
   entity-cache-timeout: 86400000
   
server:
  port: 7779
  ssl:
    enabled: false