/* Generated By:JavaCC: Do not edit this line. AnalysisPipelineInterpreterConstants.java */
package com.avaya.cap;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalysisPipelineInterpreterConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 7;
  /** RegularExpression Id. */
  int PIPELINE = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\f\"",
    "\" \"",
    "<token of kind 6>",
    "<IDENTIFIER>",
    "\">\"",
    "\",\"",
    "\";\"",
  };

}
